### ISSUE TITLE
Error for jquery-ui-rails v6

### ISSUE THREAD

**Issue by buren** [justarrived/just_match_api#721]
When precompiling assets the following error is raised:

```
Sprockets::FileNotFound: couldn't find file 'jquery-ui/datepicker' with type 'application/javascript'
 Checked in these paths:
 /app/assets/javascripts
 /app/assets/stylesheets
 /vendor/assets/javascripts
 /vendor/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/chosen-rails-1.5.2/vendor/assets/images
 /vendor/bundle/ruby/2.3.0/gems/chosen-rails-1.5.2/vendor/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/chosen-rails-1.5.2/vendor/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/blazer-1.7.5/app/assets/fonts
 /vendor/bundle/ruby/2.3.0/gems/blazer-1.7.5/app/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/blazer-1.7.5/app/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/chartkick-2.1.2/app/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/chartkick-2.1.2/vendor/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/activeadmin-1.0.0.pre4/app/assets/images
 /vendor/bundle/ruby/2.3.0/gems/activeadmin-1.0.0.pre4/app/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/activeadmin-1.0.0.pre4/app/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/coffee-rails-4.2.1/lib/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/jquery-ui-rails-6.0.1/app/assets/images
 /vendor/bundle/ruby/2.3.0/gems/jquery-ui-rails-6.0.1/app/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/jquery-ui-rails-6.0.1/app/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/jquery-rails-4.2.1/vendor/assets/javascripts
 /vendor/bundle/ruby/2.3.0/gems/formtastic-3.1.4/app/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/bourbon-4.2.7/app/assets/stylesheets
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/resolve.rb:65:in `resolve!'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/context.rb:88:in `resolve'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:259:in `resolve_with_compat'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/context.rb:142:in `require_asset'
 /vendor/bundle/ruby/2.3.0/gems/activeadmin-1.0.0.pre4/app/assets/javascripts/active_admin/jquery_ui.js.erb:7:in `_evaluate_template'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/erb_processor.rb:26:in `call'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/erb_processor.rb:13:in `call'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `block in call'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:134:in `block in find'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:133:in `each'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:133:in `find'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:185:in `compile'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/rake/sprocketstask.rb:147:in `with_logger'
 /vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
 /vendor/bundle/ruby/2.3.0/gems/airbrake-5.6.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
 /vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
 Tasks: TOP => assets:precompile
 (See full trace by running task with --trace)
```

**Comment by buren** [comment]
See https://github.com/justarrived/just_match_api/commit/063e6ed879fd89f794e448e503acc589e3a8881c
